<?php
/**
 * Implementation of hook_media_format_form_prepare_alter(&$form, &$form_state, $file)
 *
 *
 * Alter the WYSIWYG view mode selection form.
 *
 * Similar to a form_alter, but runs first so that modules can add
 * fields specific to a given file type (like alt tags on images) before alters
 * begin to work on the fields.
 *
 * @param array $form
 *   An associative array containing the structure of the form.
 * @param array $form_state
 *   An associative array containing the current state of the form.
 * @param object $file
 *   A file entity.
 *
 * @see media_format_form()
 */
function media_browser_edit_media_wysiwyg_format_form_prepare_alter(&$form, &$form_state, $file) {

  //grab the file ID
  $fid = $file->fid;
  //construct the path to the edit page
  $link_destination = 'file/' . $fid . '/edit';
  //set to open in a new window (protects unfinished work) and display a warning message
  $options['attributes']['target'] = '_blank';
  //$warning = 'alert("' . t('Image info will load in a new window or tab. You may still need to save changes here.') . '")';
  //$options['attributes']['onclick'] = $warning;
  //construct link
  if (module_exists('manualcrop')) {
    $linktext = t('Edit file / crop');
  } else {
    $linktext = t('Edit file details');
  }

  $link = l($linktext, $link_destination, $options);
  //insert link along with preview markup
  $form['original']['#markup'] = '<div class="media-browser-edit-link">' . $link . '</div>';
  $form['preview']['#weight'] =-2;
  $form['original']['#weight'] = -1;
  $form['options']['#weight'] =3;
}
